### ISSUE TITLE
标点挤压

### ISSUE THREAD

**Issue by hyrious** [hyrious/hyrious.github.io#1]
> https://www.bilibili.com/read/cv13473766

最近的博文中使用了手动标点挤压，比如 `）。` 实际显示更像是 `)。`（没有使用半角括号），这里并没有用脚本处理而是手动给这个 `）` 加了个 css：

```css
.half-shrink-right { margin-right: -.5em } /* 用 margin-inline-end 更好 */
```

实际使用时，还有以下几点注意事项：

- 中文标点和英文并排时，最好挤压并空格：

  ```html
  abc <span shrink-left>（</span> def
  ```

  但是也有例外，比如英文语境就希望连起来的标点 `abc：喵喵喵` 。

  有标准会说用 1/4 中文空格，我手写网页就算了。

- 某些不希望空格的地方，用 `&nbsp;` 进行连接；反之，希望可以断开的地方可以插入一个 `<wbr>` 。

- `code block` 和其他文本之间最好有一个空格。

- **加粗**和<ins>下划线</ins>文本左右加空格我个人觉得反而不好看，所以没加。另外还有一种着重标记（下标点），默认样式 `<em>` 是倾斜，中文斜过来不好看，所以就没用。
